### PR TITLE
Faster LBL derivatives?

### PR DESCRIPTION
**Pull request by riclarsson**
Here's my output from the script Oliver provided in a currently open issue:

Time per pressure/temperature combination
CASE 1 - All species w/ jacobian ArrayOfSpeciesTagVMR: 1.586376s
CASE 2 - All species w/ jacobian Line::VMR           : 3.782718s
CASE 3 - All species w/o jacobian                    : 1.323047s
CASE 4 - One species at a time                       : 1.330896s

### CODE REVIEW

**Comment by olemke** [comment]
I reran case 1 and 4 through the profiler. The remaining difference now comes down to the extra time spent in `ComputeValues::operator-=` for the derivates.

Case 1
case1_5000_4

Case 4
case4_5000_4

**Comment by riclarsson** [comment]
Thank you for running the profiler, Oliver.  I will have a look.  It is definitely doing more than it should for case 1.  I think a similar cut-down in time should be possible as for frequency_loop, but I need to check.  (My initial quick-and-dirty stuff just now didn't solve it, so I need to have a more detailed look when there's time.)

**Comment by riclarsson** [comment]
New times are slightly faster.  For the same case as above (5000 frequencies):
```
Time per pressure/temperature combination
CASE 1 - All species w/ jacobian ArrayOfSpeciesTagVMR: 1.486118s
CASE 2 - All species w/ jacobian Line::VMR           : 3.820726s
CASE 3 - All species w/o jacobian                    : 1.339322s
CASE 4 - One species at a time                       : 1.349771s
```

Also for 100,000 frequencies:
```
Time per pressure/temperature combination
CASE 1 - All species w/ jacobian ArrayOfSpeciesTagVMR: 21.045467s
CASE 2 - All species w/ jacobian Line::VMR           : 64.153041s
CASE 3 - All species w/o jacobian                    : 20.579016s
CASE 4 - One species at a time                       : 20.542538s
```

In #339 the case 1 to 4 ratio was 150-200%.  It is 2-10% now.  The case 2 to 4 ratio is pretty much the same as before since it is computing the full derivative.

**Comment by riclarsson** [comment]
I'm marking this as ready for review since the previous tests showed where time was being spent.  I think the small 'regression' in case 2/3/4 is just noise.  They should not be seeing any difference that could cost time now cf the first time comparison of this PR (done at the commit before the latest)

**Comment by olemke** [comment]
I agree that the slight differences in case 2-4 are negligible. I see basically the same times for 3/4 and 2 scores even slightly lower.

```
Before cc84172
CASE 1: 1.273507
CASE 2: 2.751986
CASE 3: 1.070707
CASE 4: 1.074574

After cc84172
CASE 1: 1.129954
CASE 2: 2.709163
CASE 3: 1.071539
CASE 4: 1.075069
```

**Pull request merged**
