### PR TITLE
Python integration

### PR DESCRIPTION
**Pull request by simonpf**
- Add `arts` Python pacakge to ARTS
- Adds automatically generated conversion of `*.arts` files in the controlfiles directory
- Test now automatically also run Python version
- `ctest -R fast` passes ARTS and Python versions of tests.

### CODE REVIEW

**Comment by riclarsson** [comment]
I like this!  This will mean no more .arts file for me once in place.

I want some overview of the design choices you have made that I can probably get by reading the code.  There are so many files changed that I think the overview is easier here:

0)  Is this fully automatic or must I write "make pyarts" to install it?
1)  What are the new dependencies to make a build that sets up the full install?  Python with "pip" and Sphinx?
2)  Will it install the "import arts" option with the leading "python" interpreter?  There were several issues with Anaconda's C/C++ packages so it had to be removed from some search paths, but I would prefer it if "import arts" works in the python interpreter of Anaconda after an install is done.
3)  Are the python-tests run automatically during a "make check" or is there a "make pycheck" command that needs to run?
4)  The old environment data is set automatic now?  As in, it uses the same data/includes/src paths as CMAKE to set absolute paths to the builds?
5)  Will this work as "pip install ." or as "pip install -e ."?  The former is more inline with ARTS being a compiled language but the latter is more practical for testing, so I am unsure which is better.

And some other major/minor feature comments:

a)  Have you made sure that the initial "cmake .." command gives a list of all missing dependencies and eventual "-DCMAKE_OPTIONS_FOR_THE_INSTALL"-commands?  Or at the very least that it gives some information that all python stuff is in place?  These "messages" have really helped me when installing ARTS for others.
b)  Can you grep "typhon.arts.xml" and replace with just "arts.xml"?  Several of my tests already had some helper files in python that used typhon but only for the reading.
c)  There should be IO checks between ARTS/python for all workspace variables somehow.  Because I am fairly certain I have been neglecting typhon implementations of some of the newer classes I have been setting up.  When this is in ARTS proper instead of in typhon, I should not be allowed to make that delay even if it means it will take longer to implement some features.  So some python IO tests from the allowed workspace groups would be nice.
d)  Have you removed the "Imported C-API" text in the Workspace()-command?  It should not be needed anymore.

**Comment by olemke** [comment]
@simon Really great stuff! Thanks a lot for your work! I've just started playing around with this and it looks really good so far. A couple of things:

1. As discussed last Friday, the module should be renamed from 'arts' to 'pyarts' to match the PyPi name and avoid name conflicts on install.
2. Running 'make' installed (without asking) the current pyarts package into the user's python installation (including required dependencies). This is not good since 'make' should never touch things outside the build directory, only 'make install' should do that. I've changed the 'develop' option in setup.py to 'build' accordingly.
3. The python tests can now be executed by running 'make check-python'. All default tests except one work. For that one I get an error where a problem with an intermediate output variable name goes wrong:

```
# ctest -R python.arts.ctlfile.fast.artscomponents.regrid.TestRegridFields       
Test project /Users/u237002/Hacking/git/arts/cmake-build-reldebug
    Start 49: python.arts.ctlfile.fast.artscomponents.regrid.TestRegridFields
1/1 Test #49: python.arts.ctlfile.fast.artscomponents.regrid.TestRegridFields ...***Failed    2.09 sec
Traceback (most recent call last):
  File "/Users/u237002/Hacking/git/arts/controlfiles/artscomponents/regrid/TestRegridFields.py", line 148, in <module>
    ws.ReadXML(out=ws.y_refineREFERENCE)
  File "/Users/u237002/Hacking/git/arts/cmake-build-reldebug/python/arts/workspace/workspace.py", line 262, in __call__
    self.m.call(self.ws, *args, **kwargs)
  File "/Users/u237002/Hacking/git/arts/cmake-build-reldebug/python/arts/workspace/methods.py", line 458, in call
    + e_ptr.decode("utf8").format())
Exception: Call to ARTS WSM ReadXML failed with error: Cannot find input file: .y_refineREFERENCE.xml
```

The offending line is: 
```python
ws.ReadXML(out=ws.y_refineREFERENCE)
```

**Comment by riclarsson** [comment]
Additional question:  Will <Python.h> be available?  I have seen some examples online of using it to setup interfaces to C++ classes using something like:

```
PyObject* actual_arts_class_function(PyObject* self, PyObject* args) {
/* strict format */
}
PyMethodDef ArtsCppClassFunctions[] = {
/* more strict format */
};
struct PyModuleDef ArtsCppClassInterface {
/* even more strict format */
};

PyMODINIT_FUNC PyInit_ArtsCppClass(void) {
return PyModule_Create(&ArtsCppClassInterface);
}
```

The python interface needs to have some understanding of the memory layout for the XML-stuff to work and the above seems an easy enough way to do that.  If it works.

**Comment by simonpf** [comment]
@riclarsson 

> Is this fully automatic or must I write "make pyarts" to install it?

If CMake finds a Python 3 interpreter, it will be installed as default target but `make pyarts`
of course works as well.
    

> What are the new dependencies to make a build that sets up the full install? Python with "pip" and Sphinx?

Python 3 and Sphinx but Sphinx is only needed to build the docs. We are now also releasing binary wheels on PyPI so you can install pyarts including all required ARTS binaries
via `pip install pyarts`. An anaconda version of ARTS as a whole should also not be too difficult to realize.

> Will it install the "import arts" option with the leading "python" interpreter? There were several issues with Anaconda's C/C++ packages so it had to be removed from some search paths, but I would prefer it if "import arts" works in the python interpreter of Anaconda after an install is done.

The Python interpreter used to build `pyarts` is the one found by cmake. I admit this can be a bit of a pain to get this right so we should add some documentation on how to nudge CMake to use the right interpreter.

> Are the python-tests run automatically during a "make check" or is there a "make pycheck" command that needs to run?

They should of course be run automatically, I think Oliver's last commits take care of this.

> The old environment data is set automatic now? As in, it uses the same data/includes/src paths as CMAKE to set absolute paths to the builds?

Yes

>     Will this work as "pip install ." or as "pip install -e ."? The former is more inline with ARTS being a compiled language but the latter is more practical for testing, so I am unsure which is better.

I originally introduced a CMake variable DEVELOPER_MODE to switch between the two. But as mentioned by Oliver this should only happen when `make install` is run.

> a) Have you made sure that the initial "cmake .." command gives a list of all missing dependencies and eventual "-DCMAKE_OPTIONS_FOR_THE_INSTALL"-commands? Or at the very least that it gives some information that all python stuff is in place? These "messages" have really helped me when installing ARTS for others.

Will have a look at this.

> b) Can you grep "typhon.arts.xml" and replace with just "arts.xml"? Several of my tests already had some helper files in python that used typhon but only for the reading.

Maybe. There were some minor changes in the calling convention of WSMs to make it compatible with ARTS conventions, but this affects you only if you mixed positional and keyword arguments.

> c) There should be IO checks between ARTS/python for all workspace variables somehow. Because I am fairly certain I have been neglecting typhon implementations of some of the newer classes I have been setting up. When this is in ARTS proper instead of in typhon, I should not be allowed to make that delay even if it means it will take longer to implement some features. So some python IO tests from the allowed workspace groups would be nice.

I agree that there should be at some point, but that is out of the scope of this PR.

> d) Have you removed the "Imported C-API" text in the Workspace()-command? It should not be needed anymore.

Yes.

**Comment by olemke** [comment]
@simon Although the docker build looks good now, we have a size issue:
https://github.com/simonpf/arts/runs/505062578?check_suite_focus=true#step:3:1026
```
HTTPError: 400 Client Error: File too large. Limit for project 'pyarts' is 60 MB. See https://pypi.org/help/#file-size-limit for url: https://upload.pypi.org/legacy/
```
I'm currently running a local docker container to find out how far we are over the limit. Hopefully switching the build to Release mode (what we should do anyway) will bring down the size of the wheel enough.

**Comment by olemke** [comment]
@simon PyPi upload in release mode is working. Latest build only failed because a package with the same version already exists:
https://github.com/simonpf/arts/runs/505174484?check_suite_focus=true#step:3:1023
```
HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for url: https://upload.pypi.org/legacy/
```

**Comment by simonpf** [comment]
Great! Thanks for the help, @olemke . You can't delete packages from PyPI, which is somewhat annoying, so we'll have to wait until the version number is increased.

**Comment by olemke** [comment]
I think that is fine. Since this is the version everyone gets when installing with pip, we should not replace it on every commit. Instead we should increase the version number more regularly and then also publish those development snapshots as release on github. Then the PyPi workflow can be run automatically when those releases happen.

**Comment by riclarsson** [comment]
I managed to download and make this import.  I have no idea how to push the small changes I did to this branch, though, so I attach here the diff to upstream/master:

[text.txt](https://github.com/atmtools/arts/files/4354669/text.txt)

How can this be merged?

**Comment by olemke** [comment]
The best way would be to checkout the PR into a new branch, make your changes and then push the branch to your fork:

```bash
# I assume you don't have a branch called python_integration_contrib yet
# Create a local branch called python_integration_contrib from the pull request:
git pull upstream pull/138/head:python_integration_contrib
# Make sure you don't have any uncommitted changes in your current working copy,
# commit them or use 'git stash' to save them before proceeding
# Then checkout the pull request branch
git checkout python_integration_contrib
```

Now you can make the changes you want to contribute and commit them.

```bash
# Then push the branch to your fork
git push --set-upstream origin python_integration_contrib
# Now you can go back to your own master branch
git checkout master
```

**Comment by olemke** [comment]
Please also not that the files you added in your last PR #140 or not yet in this PR. If you only changed those, there's no point in doing what I wrote above.

**Comment by riclarsson** [comment]
I have added the things required to make #140 work to the python parts of this.  What you, Oliver, say means that my stuff here won't work at all before either #140 is mixed into this branch or this is mixed into ARTS master

**Comment by simonpf** [comment]
Anything else missing now?

**Comment by olemke** [comment]
We need to check for required Python modules for pyarts in the toplevel CMakeLists. For me, tests were failing because I didn't have the lack-parser module installed. Also, we need a python-tests directory in the toplevel where new Python-only tests can be placed. Including an infrastructure similar to arts_test_run_ctlfile, adapted for Python scripts.

**Comment by olemke** [comment]
@simon do you have any non-pushed commits on your end? Otherwise I'd like to do a force-push to your branch to merge the latest changes from master into it.

**Comment by simonpf** [comment]
> We need to check for required Python modules for pyarts in the toplevel CMakeLists. For me, tests were failing because I didn't have the lack-parser module installed. Also, we need a python-tests directory in the toplevel where new Python-only tests can be placed. Including an infrastructure similar to arts_test_run_ctlfile, adapted for Python scripts.

Alright, this will take a few more days until I will get around to doing  this.

> @simon do you have any non-pushed commits on your end? Otherwise I'd like to do a force-push to your branch to merge the latest changes from master into it.

Go ahead, my working directory is clean. While you are at it, would you mind bumping up the version number so that I can at least get the current version onto PyPI?

**Comment by olemke** [comment]
> > We need to check for required Python modules for pyarts in the toplevel CMakeLists. For me, tests were failing because I didn't have the lack-parser module installed. Also, we need a python-tests directory in the toplevel where new Python-only tests can be placed. Including an infrastructure similar to arts_test_run_ctlfile, adapted for Python scripts.
> 
> Alright, this will take a few more days until I will get around to doing this.

I will have a look at this today/tomorrow. Will keep you posted.
 
> > @simon do you have any non-pushed commits on your end? Otherwise I'd like to do a force-push to your branch to merge the latest changes from master into it.
> 
> Go ahead, my working directory is clean. While you are at it, would you mind bumping up the version number so that I can at least get the current version onto PyPI?

Done and done.

**Comment by riclarsson** [comment]
The #143 bug report made me run "make check-all" on my #141 branch.

These tests fail

```
	151 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Earth (SEGFAULT)
	153 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Mars (SEGFAULT)
	155 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Venus (SEGFAULT)
```

Is this something I did with #141 or do they also fail on this branch?

**Comment by simonpf** [comment]
> The #143 bug report made me run "make check-all" on my #141 branch.
> 
> These tests fail
> 
> 	151 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Earth (SEGFAULT)
> 	153 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Mars (SEGFAULT)
> 	155 - python.arts.ctlfile.xmldata.artscomponents.arts-xml-data.TestSurf_Venus (SEGFAULT)
> 
> Is this something I did with #141 or do they also fail on this branch?

This is fixed on this branch.

**Comment by simonpf** [comment]
@

**Comment by simonpf** [comment]
> I will have a look at this today/tomorrow. Will keep you posted.

Are you still on this? Otherwise, I will try to finish this today. Would be really nice to have this upstream.

**Comment by olemke** [comment]
I just started to add a python-tests directory, where we can have python-only checks. I think I'll manage to finish that today. Then we should be good to go for the merge.

**Comment by olemke** [comment]
The latest commits add a controlfiles-python directory including one small example script. It's meant for new, purely pyarts-based tests/controlscripts. They are executed together with the converted controlfiles by the check-python target. For easier testing , there's also a `make check-pyarts-only` target that solely runs the jobs from the controlfiles-python directory. The setup for tests is pretty much the same as in the controlfiles directory, just that instead of an .arts file, you add a .py file and the macro to add a test is called `arts_test_run_pyfile`. @simonpf from my side, the branch is ready to be merged. The annoying Python problem in the macOS GitHub action can be fixed later.

**Comment by simonpf** [comment]
> The latest commits add a controlfiles-python directory including one small example script. It's meant for new, purely pyarts-based tests/controlscripts. They are executed together with the converted controlfiles by the check-python target. For easier testing , there's also a make check-pyarts-only target that solely runs the jobs from the controlfiles-python directory. The setup for tests is pretty much the same as in the controlfiles directory, just that instead of an .arts file, you add a .py file and the macro to add a test is called arts_test_run_pyfile. @simonpf from my side, the branch is ready to be merged. The annoying Python problem in the macOS GitHub action can be fixed later.

Awesome! Great work!

**Comment by olemke** [comment]
@simonpf Credit is all yours. You did all the heavy lifting!

**Pull request merged**
