### PR TITLE
Test implementation of weighted RT emission

### PR DESCRIPTION
**Pull request by riclarsson**
@erikssonpatrick This is the code I talked about.  It is just tested to run and not for the physics being good.  Some test code to make this work is required to figure out if it is even remotely good.

Change this in m_rte.cc to test the new code "RadiativeTransferSolver::Emission"  → "RadiativeTransferSolver::WeightedEmission".  It does not pass the tests, but it does pass several tests that do use the iyEmissionStandard code when you do the this change.

### CODE REVIEW

**Comment by olemke** [comment]
Should this be merged or this is just here for testing?

**Comment by riclarsson** [comment]
This should be left as a branch that Patrick and I can iterate on.  If and when it works it should be merged, not before.

**Comment by olemke** [comment]
If it's supposed to be a branch, you should put it in a branch on your fork.

**Comment by riclarsson** [comment]
I am closing this as nothing is happening and it is  messing up my ARTS fork

**Pull request closed without merging**
