### PR TITLE
Fix tests

### LINKED ISSUE #671: some of the tests still failed with make check-all
I have recompiled the source code including lastest merge #670, and executing 'make check-all'; there are some of tests still failing, 
There are three types of failed tests:
(1) missing control file 'planet_mars.arts', 'planet_jupiter.arts' ...
(2) 'Dynamic tables not yet supported with threads.'
(3) abs_xsec_agenda_checkedCalc is not a known workspace method.

maybe the corresponding xml-data needs to be updated?
the complete check output are as follows:

[check_results.txt](https://github.com/atmtools/arts/files/12605558/check_results.txt)

### PR DESCRIPTION
**Pull request by olemke**
Fix failing tests.

Remove tests that use no longer supported features (RadioLink, Relmat).

Planetary toolbox removed.

Speed up "fast" instrument tests by reducing number of species (MVIRI, SEVIRI, HIRS).

TestIyActive_wfuns uncovered a serious bug where dpnd_field_dx was not properly initialized.

Fixed error in TestHIRS_reference. `f_gridFromSensorHIRS` ignored leading/trailing zeros in the `backend_channel_response` to determine the lowest required frequency in `f_backend` while `sensor_responseBackend` did not. Adjusted `f_gridFromSensorHIRS` accordingly.

Closes #671

### CODE REVIEW

**Comment by olemke** [comment]
@erikssonpatrick Please have a look at [4255c20](https://github.com/atmtools/arts/pull/677/commits/4255c203ac0053cf85709962f91f03c145d1c7b2) and let me know if you're ok with the changes

**Comment by olemke** [comment]
@erikssonpatrick, @stefanbuehler Any comments from your side before I merge this?

**Comment by stefanbuehler** [comment]
Ok from my side.

**Comment by erikssonpatrick** [comment]
Looks fine.

**Pull request merged**
