### PR TITLE
Revision of Jacobian testing

### PR DESCRIPTION
**Pull request by erikssonpatrick**
This should conclude my present work on tests of the Jacobian calculations. 
Closed the previous pull request when I found another issue. Did not manage to reopen that one and now made a new pull request.
Details in the commit comments.

### CODE REVIEW

**Comment by riclarsson** [comment]
Please explain why this requires an extra workspace variable and not just a GIN for the relevant function.  Which is the relevant function?

**Comment by erikssonpatrick** [comment]
@riclarsson See my comment regarding the issue on Wind Jacobian

**Comment by riclarsson** [comment]
Right, I think this pull should remove the addition of abs_f_interp, and that we should instead look into the cause of the problem.  This plaster seems excessive since it changes functions that are not relevant for the error itself.  (Also, at least sometimes, if you use the hashtag to write the number as #55 , github seems to create an automatic link.  Just an FYI for the future.)

**Comment by erikssonpatrick** [comment]
@riclarsson If you can find a solution to this that removes the constraint of abs_interp_f>0, that is of course excellent. I can then rewind that part of this pull request. But until we know that is possible, I prefer that this pull request is not delayed as it involves a number of commits and would be nice to get them into the master.

**Comment by olemke** [comment]
Merge this for now. Please continue discussion in #55

**Pull request merged**
