### PR TITLE
Use MDSPAN instead of matpack as a mathematical core 

### PR DESCRIPTION
**Pull request by riclarsson**
This is a major update.

In C++23 MDSPAN is accepted as the core way for which C++ multidimensional data should be viewed.  I jumped the gun and downloaded the implementation of [MDSPAN](https://github.com/kokkos/mdspan) and attempted to replace `matpack` with this as the core.

Everything is working now and I think it would be good to switch out `matpack` for something that at least will be more standards compliant in the future.

The reimplementation of `matpack` features is fairly close to the original `matpack`, though a few core concepts are different.  This is why so many files have been touched.

The differences that exists are:
1. It is no longer allowed to cast from `Numeric&` to a `VectorView` or from a `VectorView` to a `MatrixView` implicitly.  You have to put `VectorView{MyNumeric}` or `MatrixView{MyVectorView}`
2. There are no longer a uniform grid `Vector` constructor.  I provide `uniform_grid` as a standalone function to create a uniformly gridded `Vector`.
3. There is also no longer any `sum()` member function to the `matpack` types.  Again, a standalone implementation exist that can be used instead.
4. You can get a data pointer not by calling `get_c_array()` but by calling `data_handle()` or `unsafe_data_handle()`, depending on type.
5. There is no longer any inheritances between the views and the data holder so a `VectorView&` cannot be constructed from a `Vector&`.  You can still implicitly construct a `VectorView` from a `Vector&`.  The same is true for the `Const...` version
6. The one implicit reference construction is towards a type I call `ExhaustiveVectorView`.  This type is viewing data exhaustively, i.e., it knows that the next thing in memory either is part of its view or not part of its data at all.
7. `begin/end` and `elem_begin/elem_end` exist to give random access iteration access to the a subview for `begin/end` and to all the elements for `elem_begin/elem_end`.
8. `mult_general` is removed.  Just call `mult` everywhere and the rest is fixed in the call
9. To create a new type is easier.  A `Tensor99` is created by putting `99` instead of `7` in the template that creates the typename `Tensor7`.

This exhaustiveness is an important new thing.  Accessing a `Tensor7` with `MyTensor7(0, 0, 0, joker, joker, joker, joker)` returns an `ExhaustiveTensor4View`, since all the data it points at is continuous.  This type can implicitly create a `Tensor4View`, but it is then less optimal for accessing individual elements since it (AS IS THE CASE TODAY) then does not know that it is exhaustive anymore.  The non-exhaustive types do not have access to `data_handle` but must use `unsafe_data_handle`.

Of course, it is very limited today that we use the `Exhaustive` versions anywhere.  I lest the non-exhaustive versions in place throughout the code.  This is mostly important to be aware of in the future.

### CODE REVIEW

**Comment by riclarsson** [comment]
So here are all the performance tests in the last perf-setup.  The operation is in the left colum.  The top row contains "gcc" or "clang" to indicate compiler, "new" or "old" to indicate this implementation or the old matpack, and "rel" or "dbg" to indicate cmake-mode "Release" or "RelWithDebInfo".  There are three tests for each operation: "vec" or "mat" means it is an operation that took a pure "Vector" or "Matrix", "exview" or "exmview" means that it was for an exhaustive view of "Vector" or "Matrix", and "view" or "mview" that is for a normal view of the data.  The old matpack does not have exhaustive view so they are typedef:d to views for those tests so that I can run mostly the same code.  The only difference is that "sum" is not a member function but a standalone function in the new code.  The times are given in seconds.  I will break this up in a few more comments about the individual tests, but I think the full data should be available for all to see.

| OPERATION | new-clang-dbg | new-clang-rel | new-gcc-dbg | new-gcc-rel | old-clang-dbg | old-clang-rel | old-gcc-dbg | old-gcc-rel |
|--|--|--|--|--|--|--|--|--|
| sum(vec) | 0.465 | 0.465 | 0.117 | 0.117 | 0.466 | 0.466 | 0.466 | 0.466 |
| sum(exview) | 0.466 | 0.465 | 0.117 | 0.117 | 0.466 | 0.465 | 0.466 | 0.466 |
| sum(view) | 0.624 | 0.465 | 0.862 | 0.468 | 0.466 | 0.465 | 0.466 | 0.466 |
| mean(vec) | 0.465 | 0.465 | 0.118 | 0.117 | 0.466 | 0.466 | 0.466 | 0.466 |
| mean(exview) | 0.466 | 0.465 | 0.117 | 0.117 | 0.466 | 0.466 | 0.466 | 0.466 |
| mean(view) | 0.622 | 0.465 | 0.863 | 0.466 | 0.466 | 0.466 | 0.466 | 0.466 |
| nanmean(vec) | 0.467 | 0.466 | 0.157 | 0.157 | 0.621 | 0.621 | 0.467 | 0.467 |
| nanmean(exview) | 0.469 | 0.466 | 0.157 | 0.157 | 0.621 | 0.621 | 0.468 | 0.467 |
| nanmean(view) | 0.624 | 0.466 | 1.737 | 0.466 | 0.622 | 0.621 | 0.467 | 0.467 |
| vec * vec | 0.026 | 0.026 | 0.031 | 0.031 | 0.124 | 0.124 | 0.124 | 0.124 |
| exview * exview | 0.093 | 0.093 | 0.124 | 0.124 | 0.124 | 0.124 | 0.124 | 0.124 |
| view * view | 0.093 | 0.093 | 0.124 | 0.124 | 0.124 | 0.124 | 0.124 | 0.124 |
| vec = mat * vec | 0.124 | 0.135 | 0.12 | 0.121 | 0.12 | 0.125 | 0.133 | 0.126 |
| exview = exmview * exview | 0.122 | 0.121 | 0.121 | 0.121 | 0.135 | 0.127 | 0.128 | 0.135 |
| view = mview * view | 0.121 | 0.118 | 0.124 | 0.12 | 0.119 | 0.125 | 0.119 | 0.135 |
| mat = mat * mat | 0.232 | 0.23 | 0.231 | 0.234 | 0.227 | 0.231 | 0.24 | 0.242 |
| exmview = exmview * exmview | 0.232 | 0.231 | 0.23 | 0.234 | 0.227 | 0.231 | 0.239 | 0.241 |
| mview = mview * mview | 0.233 | 0.231 | 0.23 | 0.233 | 0.227 | 0.231 | 0.239 | 0.241 |
| vec = 1 | 0.064 | 0.064 | 0.156 | 0.078 | 0.079 | 0.074 | 0.156 | 0.079 |
| exview = 1 | 0.065 | 0.068 | 0.156 | 0.084 | 0.157 | 0.157 | 0.156 | 0.156 |
| view = 1 | 0.698 | 0.065 | 1.073 | 0.086 | 0.156 | 0.156 | 0.157 | 0.156 |
| vec += 1.33 | 0.084 | 0.084 | 0.202 | 0.115 | 0.199 | 0.2 | 0.2 | 0.2 |
| exview += 1.33 | 0.083 | 0.083 | 0.201 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| view += 1.33 | 0.635 | 0.083 | 1.097 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| vec -= 1.5 | 0.083 | 0.083 | 0.201 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| exview -= 1.5 | 0.083 | 0.083 | 0.2 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| view -= 1.5 | 0.622 | 0.083 | 1.088 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| vec *= 3.5 | 0.083 | 0.083 | 0.201 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| exview *= 3.5 | 0.083 | 0.083 | 0.198 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| view *= 3.5 | 0.622 | 0.083 | 1.086 | 0.113 | 0.199 | 0.199 | 0.199 | 0.199 |
| vec /= 7.77 | 0.091 | 0.091 | 0.192 | 0.117 | 0.191 | 0.191 | 0.192 | 0.192 |
| exview /= 7.77 | 0.091 | 0.091 | 0.19 | 0.117 | 0.191 | 0.191 | 0.191 | 0.191 |
| view /= 7.77 | 0.636 | 0.091 | 0.885 | 0.117 | 0.191 | 0.191 | 0.191 | 0.191 |
| mat = 1 | 0.051 | 0.051 | 0.125 | 0.062 | 0.052 | 0.063 | 0.125 | 0.063 |
| exmview = 1 | 0.054 | 0.053 | 0.124 | 0.064 | 0.125 | 0.125 | 0.125 | 0.125 |
| mview = 1 | 0.563 | 0.054 | 0.857 | 0.063 | 0.126 | 0.126 | 0.125 | 0.126 |
| mat += 1.33 | 0.067 | 0.067 | 0.161 | 0.092 | 0.159 | 0.16 | 0.16 | 0.161 |
| exmview += 1.33 | 0.067 | 0.067 | 0.16 | 0.091 | 0.159 | 0.159 | 0.159 | 0.159 |
| mview += 1.33 | 0.502 | 0.066 | 0.873 | 0.091 | 0.159 | 0.159 | 0.159 | 0.159 |
| mat -= 1.5 | 0.067 | 0.067 | 0.16 | 0.091 | 0.16 | 0.159 | 0.159 | 0.159 |
| exmview -= 1.5 | 0.067 | 0.066 | 0.161 | 0.091 | 0.16 | 0.159 | 0.159 | 0.159 |
| mview -= 1.5 | 0.5 | 0.067 | 0.871 | 0.091 | 0.16 | 0.159 | 0.16 | 0.159 |
| mat *= 3.5 | 0.066 | 0.067 | 0.161 | 0.091 | 0.159 | 0.159 | 0.159 | 0.159 |
| exmview *= 3.5 | 0.066 | 0.066 | 0.161 | 0.091 | 0.159 | 0.159 | 0.159 | 0.16 |
| mview *= 3.5 | 0.5 | 0.067 | 0.871 | 0.091 | 0.159 | 0.159 | 0.159 | 0.159 |
| mat /= 7.77 | 0.073 | 0.073 | 0.152 | 0.093 | 0.153 | 0.153 | 0.153 | 0.153 |
| exmview /= 7.77 | 0.073 | 0.073 | 0.153 | 0.094 | 0.154 | 0.153 | 0.153 | 0.153 |
| mview /= 7.77 | 0.509 | 0.073 | 0.845 | 0.094 | 0.153 | 0.153 | 0.153 | 0.153 |
| vec += vec | 1.125 | 0.14 | 1.073 | 0.157 | 0.338 | 0.338 | 0.234 | 0.227 |
| exview += exview | 1.126 | 0.14 | 1.072 | 0.157 | 0.338 | 0.338 | 0.234 | 0.226 |
| view += view | 1.114 | 0.14 | 0.255 | 0.157 | 0.338 | 0.338 | 0.234 | 0.226 |
| vec -= vec | 1.123 | 0.14 | 1.075 | 0.158 | 0.338 | 0.338 | 0.234 | 0.226 |
| exview -= exview | 1.116 | 0.14 | 1.075 | 0.158 | 0.339 | 0.338 | 0.234 | 0.226 |
| view -= view | 1.11 | 0.14 | 0.251 | 0.158 | 0.338 | 0.338 | 0.234 | 0.227 |
| vec *= vec | 1.117 | 0.14 | 1.074 | 0.157 | 0.338 | 0.338 | 0.234 | 0.227 |
| exview *= exview | 1.116 | 0.14 | 1.072 | 0.158 | 0.338 | 0.338 | 0.234 | 0.227 |
| view *= exview | 1.113 | 0.14 | 0.252 | 0.158 | 0.338 | 0.338 | 0.234 | 0.226 |
| vec /= vec | 1.103 | 0.141 | 1.092 | 0.164 | 0.346 | 0.346 | 0.25 | 0.237 |
| exview /= exview | 1.103 | 0.14 | 1.091 | 0.164 | 0.346 | 0.346 | 0.249 | 0.238 |
| view /= view | 1.114 | 0.14 | 0.262 | 0.164 | 0.346 | 0.346 | 0.25 | 0.238 |
| mat += mat | 0.84 | 0.112 | 0.71 | 0.126 | 0.186 | 0.184 | 0.183 | 0.182 |
| exmview += exmview | 0.837 | 0.112 | 0.711 | 0.127 | 0.186 | 0.182 | 0.183 | 0.183 |
| mview += mview | 0.885 | 0.112 | 0.211 | 0.126 | 0.185 | 0.184 | 0.183 | 0.181 |
| mat -= mat | 0.842 | 0.112 | 0.196 | 0.126 | 0.186 | 0.184 | 0.183 | 0.182 |
| exmview -= exmview | 0.841 | 0.112 | 0.196 | 0.126 | 0.187 | 0.185 | 0.183 | 0.182 |
| mview -= mview | 0.886 | 0.112 | 0.213 | 0.126 | 0.188 | 0.185 | 0.183 | 0.184 |
| mat *= mat | 0.84 | 0.112 | 0.198 | 0.126 | 0.188 | 0.181 | 0.183 | 0.182 |
| exmview *= exmview | 0.841 | 0.112 | 0.197 | 0.126 | 0.188 | 0.183 | 0.183 | 0.18 |
| mview *= mview | 0.888 | 0.112 | 0.213 | 0.126 | 0.188 | 0.184 | 0.183 | 0.183 |
| mat /= mat | 0.827 | 0.112 | 0.712 | 0.131 | 0.188 | 0.194 | 0.192 | 0.194 |
| exmview /= exmview | 0.826 | 0.112 | 0.711 | 0.131 | 0.189 | 0.195 | 0.192 | 0.192 |
| mview /= mview | 0.891 | 0.112 | 0.221 | 0.131 | 0.188 | 0.195 | 0.192 | 0.192 |

**Comment by riclarsson** [comment]
All the following tests are the ratio between OLD matpack and NEW matpack.  A number above 1.0 means the NEW matpack is performing BETTER than the old matpack.  The same naming scheme applies as for my post above.

These are the results for summing all the elements in a vector.  There were 500000000 elements put into the vector.  In short, DEBUG builds are slower for views than before.  For Vector and the new ExhaustiveVector, gcc performs several times faster.  There is no difference for clang release.
| TEST | sum(vec) | sum(exview) | sum(view) |
|--|--|--|--|
| DEBUG gcc | 4.0 | 4.0 | 0.5 |
| DEBUG clang | 1.0 | 1.0 | 0.7 |
| RELEASE gcc | 4.0 | 4.0 | 1.0 |
| RELEASE clang | 1.0 | 1.0 | 1.0 |

These are the results for finding the mean all the elements in a vector.  There were 500000000 elements put into the vector.  In short, DEBUG builds are slower for views than before.  For Vector and the new ExhaustiveVector, gcc performs several times faster.  There is no difference for clang release.
| TEST | mean(vec) | mean(exview) | mean(view) |
|--|--|--|--|
| DEBUG gcc | 3.9 | 4.0 | 0.5 |
| DEBUG clang | 1.0 | 1.0 | 0.7 |
| RELEASE gcc | 4.0 | 4.0 | 1.0 |
| RELEASE clang | 1.0 | 1.0 | 1.0 |

These are the results for finding the mean all the elements in a vector ignoring NAN.  There were 500000000 elements put into the vector.  In short, DEBUG builds are slower for views than before.  For Vector and the new ExhaustiveVector, gcc performs several times faster.  There is no difference for clang release.
| TEST | nanmean(vec) | nanmean(exview) | nanmean(view) |
|--|--|--|--|
| DEBUG gcc | 3.0 | 3.0 | 0.3 |
| DEBUG clang | 1.3 | 1.3 | 1.0 |
| RELEASE gcc | 3.0 | 3.0 | 1.0 |
| RELEASE clang | 1.3 | 1.3 | 1.3 |

These are the results for the dot-produce between vectors.  For clang, everything is faster.  For gcc, only Vector has improved.
| TEST | vec * vec | exview * exview | view * view |
|--|--|--|--|
| DEBUG gcc | 4.0 | 1.0 | 1.0 |
| DEBUG clang | 4.7 | 1.3 | 1.3 |
| RELEASE gcc | 4.0 | 1.0 | 1.0 |
| RELEASE clang | 4.7 | 1.3 | 1.3 |

These are the tests for Matrix-Vector multiplication.  These give you only noise, as the underlying lapack-implementation is still used.  There is not improvement or degradation anywhere.
| TEST | vec = mat * vec | exview = exmview * exview | view = mview * view |
|--|--|--|--|
| DEBUG gcc | 1.1 | 1.1 | 1.0 |
| DEBUG clang | 1.0 | 1.1 | 1.0 |
| RELEASE gcc | 1.0 | 1.1 | 1.1 |
| RELEASE clang | 0.9 | 1.1 | 1.1 |

These are the tests for Matrix-Matrix multiplication.  These give you only noise, as the underlying lapack-implementation is still used.  There is not improvement or degradation anywhere.
| TEST | mat = mat * mat | exmview = exmview * exmview | mview = mview * mview |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 1.0 |
| DEBUG clang | 1.0 | 1.0 | 1.0 |
| RELEASE gcc | 1.0 | 1.0 | 1.0 |
| RELEASE clang | 1.0 | 1.0 | 1.0 |

These are the tests for setting a Vector to a constant.  The loop over all elements seem better for the views than they were before but the loops over Vector is the same as before.  However, there is a lot more DEBUG information available in the new code so DEBUG builds produce severely worse runtime in the NEW code.
| TEST | vec = 1 | exview = 1 | view = 1 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.1 |
| DEBUG clang | 1.2 | 2.4 | 0.2 |
| RELEASE gcc | 1.0 | 1.8 | 1.8 |
| RELEASE clang | 1.2 | 2.3 | 2.4 |

These are the tests for adding a constant to a Vector.  The results are essentially the same as for setting a value (except it seems old matpack did not optimise this as well for Vector as the constant setting routine)
| TEST | vec += 1.33 | exview += 1.33 | view += 1.33 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.7 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for subtracting a constant from a Vector.  The results are essentially the same as for setting a value (except it seems old matpack did not optimise this as well for Vector as the constant setting routine)
| TEST | vec -= 1.5 | exview -= 1.5 | view -= 1.5 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.8 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for multiplying a Vector with a constant.  The results are essentially the same as for setting a value (except it seems old matpack did not optimise this as well for Vector as the constant setting routine)
| TEST | vec *= 3.5 | exview *= 3.5 | view *= 3.5 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.8 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for dividing a Vector with a constant.  The results are essentially the same as for setting a value (except it seems old matpack did not optimise this as well for Vector as the constant setting routine)
| TEST | vec /= 7.77 | exview /= 7.77 | view /= 7.77 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.1 | 2.1 | 0.3 |
| RELEASE gcc | 1.6 | 1.6 | 1.6 |
| RELEASE clang | 2.1 | 2.1 | 2.1 |

These are the test for setting a Matrix to a constant.  There are no differences to the Vector results
| TEST | mat = 1 | exmview = 1 | mview = 1 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.1 |
| DEBUG clang | 1.0 | 2.3 | 0.2 |
| RELEASE gcc | 1.0 | 2.0 | 2.0 |
| RELEASE clang | 1.2 | 2.4 | 2.3 |

These are the test for adding a constant to a Matrix.  There are no differences to the Vector results
| TEST | mat += 1.33 | exmview += 1.33 | mview += 1.33 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.7 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the test for subtracting a constant from a Matrix.  There are no differences to the Vector results
| TEST | mat -= 1.5 | exmview -= 1.5 | mview -= 1.5 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.8 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the test for multiplying a constant with a Matrix.  There are no differences to the Vector results
| TEST | mat *= 3.5 | exmview *= 3.5 | mview *= 3.5 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.4 | 2.4 | 0.3 |
| RELEASE gcc | 1.8 | 1.8 | 1.8 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the test for dividing a Matrix with a constant.  There are no differences to the Vector results
| TEST | mat /= 7.77 | exmview /= 7.77 | mview /= 7.77 |
|--|--|--|--|
| DEBUG gcc | 1.0 | 1.0 | 0.2 |
| DEBUG clang | 2.1 | 2.1 | 0.3 |
| RELEASE gcc | 1.6 | 1.6 | 1.6 |
| RELEASE clang | 2.1 | 2.1 | 2.1 |

These are the tests for adding a Vector to another Vector.   There is a large time degradation for DEBUG but RELEASE runtime is faster.
| TEST | vec += vec | exview += exview | view += view |
|--|--|--|--|
| DEBUG gcc | 0.2 | 0.2 | 0.9 |
| DEBUG clang | 0.3 | 0.3 | 0.3 |
| RELEASE gcc | 1.4 | 1.4 | 1.4 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for removing a Vector from another Vector.   Same results as the addition
| TEST | vec -= vec | exview -= exview | view -= view |
|--|--|--|--|
| DEBUG gcc | 0.2 | 0.2 | 0.9 |
| DEBUG clang | 0.3 | 0.3 | 0.3 |
| RELEASE gcc | 1.4 | 1.4 | 1.4 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for multiplying a Vector with another Vector.   Same results as the addition
| TEST | vec *= vec | exview *= exview | view *= exview |
|--|--|--|--|
| DEBUG gcc | 0.2 | 0.2 | 0.9 |
| DEBUG clang | 0.3 | 0.3 | 0.3 |
| RELEASE gcc | 1.4 | 1.4 | 1.4 |
| RELEASE clang | 2.4 | 2.4 | 2.4 |

These are the tests for dividing a Vector with another Vector.   Same results as the addition
| TEST | vec /= vec | exview /= exview | view /= view |
|--|--|--|--|
| DEBUG gcc | 0.2 | 0.2 | 1.0 |
| DEBUG clang | 0.3 | 0.3 | 0.3 |
| RELEASE gcc | 1.4 | 1.4 | 1.4 |
| RELEASE clang | 2.5 | 2.5 | 2.5 |

These are the tests for adding a matrix to another matrix.  The results are the same as above for the Vector-Vector operation
| TEST | mat += mat | exmview += exmview | mview += mview |
|--|--|--|--|
| DEBUG gcc | 0.3 | 0.3 | 0.9 |
| DEBUG clang | 0.2 | 0.2 | 0.2 |
| RELEASE gcc | 1.4 | 1.4 | 1.4 |
| RELEASE clang | 1.7 | 1.6 | 1.7 |

These are the tests for removing a matrix from another matrix.  The results are the same as above for the Vector-Vector operation
| TEST | mat -= mat | exmview -= exmview | mview -= mview |
|--|--|--|--|
| DEBUG gcc | 0.9 | 0.9 | 0.9 |
| DEBUG clang | 0.2 | 0.2 | 0.2 |
| RELEASE gcc | 1.4 | 1.4 | 1.5 |
| RELEASE clang | 1.7 | 1.7 | 1.7 |

These are the tests for multiplying a matrix with another matrix.  The results are the same as above for the Vector-Vector operation
| TEST | mat *= mat | exmview *= exmview | mview *= mview |
|--|--|--|--|
| DEBUG gcc | 0.9 | 0.9 | 0.9 |
| DEBUG clang | 0.2 | 0.2 | 0.2 |
| RELEASE gcc | 1.4 | 1.4 | 1.5 |
| RELEASE clang | 1.6 | 1.6 | 1.6 |

These are the tests for dividing a matrix with another matrix.  The results are the same as above for the Vector-Vector operation
| TEST | mat /= mat | exmview /= exmview | mview /= mview |
|--|--|--|--|
| DEBUG gcc | 0.3 | 0.3 | 0.9 |
| DEBUG clang | 0.2 | 0.2 | 0.2 |
| RELEASE gcc | 1.5 | 1.5 | 1.5 |
| RELEASE clang | 1.7 | 1.7 | 1.7 |

I will have a look at improving some of the DEBUG results but I don't think they are as important as the RELEASE results.  So in short, the conclusion is that the new matpack is overall a lot faster than the old one.

**Comment by riclarsson** [comment]
[4cb565b](https://github.com/atmtools/arts/pull/590/commits/4cb565b74636bbc80d37b5fd96b8b6059642dc47) fixes DEBUG for Vector/Matrix and their exhaustive partners, runtime degradation in the tables above.  There is still degradation for VectorView/MatrixView in runtime costs.

**Comment by riclarsson** [comment]
Unless the commit breaks anything, I am done now.

The average performance improvement is quite good for common use-cases.  There are probably some small optimisations that can be done in various parts of the code but I think it is in a good state.  The tables above all speak how the performance is quite a lot better for almost all release builds, which is what we should go for.

@stefanbuehler , @erikssonpatrick , @olemke , I will go through this at the next arts weekly meeting.  I think it is possible to merge before then so that this can be incorporated into the active atm-branch.  Any objections?

@olemke , please have a look through the code whenever you have time.  I have removed all PCH, so they should perhaps be added back.  I don't really know how that works and I am not even sure if I am using PCH so you are better suited for this.  If you find nothing else and there are no other objections, I think it would be fine to merge after that is added back.

**Comment by olemke** [comment]
@riclarsson: I had a look at adding PCH explicitly for matpack. I don't think it is necessary as it would not give any compilation time advantage. The reason for this is that we build PCH files for artscore and the python interface. Matpack header files are already indirectly getting pulled into the PCH files of those targets. It would only speed up compilation if we had several targets that were linked solely against matpack and not artscore.

**Comment by olemke** [comment]
[Here is gist with the results of a benchmark run](https://gist.github.com/olemke/74b5254f0478e4216820f150100c1b00) of the current mdspan implementation on Linux (DKRZ Levante Supercomputer, AMD Epyc, RHEL 8.5). It shows similar speed improvements as @riclarsson's benchmark on macOS. The performance drops in the debug version that were present in the macOS tests are mostly gone, presumably due to code optimizations made since that run was performed.

**Review by olemke — APPROVED** [review]
As discussed in the ARTS meeting, this is good to be merged with the promise that the developer guide will be updated soon.

**Pull request merged**
